name: {name}
app_insights_enabled: true
model: {model}
code_configuration:
  code: 
    local_path: ../
  scoring_script: score.py
environment: azureml:pytorch-lightning-gpu-deploy:3
instance_type: Standard_NC6s_v3
scale_settings:
  scale_type: manual
  instance_count: 1
  min_instances: 1
  max_instances: 1