$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: vision-endpoint
type: online
target: azureml:aks-hci-2cpu6gb
auth_mode: key
traffic:
  blue: 100

deployments:
  - name: blue
    app_insights_enabled: true
    model: azureml:rocksie-model:1
    code_configuration:
      code: 
        local_path: ../
      scoring_script: score.py
    environment: azureml:pytorch-lightning-cpu-deploy:1
    instance_type: defaultInstanceType
    scale_settings:
      scale_type: manual
      instance_count: 1
    request_settings:
      request_timeout_ms: 1000
      max_concurrent_requests_per_instance: 1
      max_queue_wait_ms: 1000
    resource_requirements:
      cpu: 1
      memory_in_gb: 5
    liveness_probe:
      initial_delay: 10
      period: 10
      timeout: 10
      success_threshold: 1
      failure_threshold: 1